# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cad10b7beb694719209471aa7a4e7f722c91e580d091e7cc3d73c396c7f60fe3c8429f7065ca2b8db91297621373addbe8c82f2b625866de5d6f5c89fe753c4

test:
  secret_key_base: be91785c9f4fd67ad71333bf15fd1d19c1092c9a7925b0da4b0379edd4a50b6a36001995255043610fe1f6908523f39dcf0cf8815e134f52666c2977b6dc1b10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
